version: 3
debug: false

PlayersRequired: 1 #This is to prevent spam if there's only 1 or 2 people killing the mob privately, there's no limit!
PlacesToBroadcast: 10 #How much places to broadcast.
PlacePrefix:
  1: "&a"
  2: "&b"
  3: "&e"
  123: "This pos will have long prefix!"
  default: "&6"

Damage:
  required: 0 #How much damage the player has to dealt to get included to the leaderboard, set to 0 to disable

Warmup:
  damage: 1 #How much damage the mob have to take to start the leaderboard, set to 0 to disable
  reset:
    interval: 600 #Time for the leaderboard to reset, set to 0 to disable

Reset:
  resetHealth: true #Will the boss reset its health?
  damage: 1 #How much damage the mob have to take for the leaderboard to not get cleared
  interval: 600 #Time for the leaderboard to reset

Messages:
  #Should the plugin broadcast the messages when mob spawns or dies
  broadcast: true

  #Placeholders avalable: %place_color%, %place%, %mob_name%, %percentage%
  MobSpawn:
    messages:
    - "&8&l&m------<--------------->------"
    - "   &8<&a!&8> &7Mob named: %mob_name% spawned at (x: %x%, y: %y%, z: %z%)"
    - "&8&l&m------<--------------->------"
    title:
      enabled: true
      title: "%mob_name% spawned"
      subTitle: "x: %x%, y: %y%, z: %z%"
      fadeIn: 1
      stay: 1
      fadeOut: 1
    actionbar:
      enabled: true
      message: "%mob_name% spawned"
  MobDead:
    #Placeholders avalable: %mob_top_taken_{pos}%, %mob_top_dealt_{pos}%
    damageDealt:
      header: "&8&l&m------<&r &cMob %mob_name% has died! &8&l&m>------"
      footer: "&8&l&m------&c&l<>&8&l&m---&8&l&m---&c&l<>&8&l&m------"
      #Placeholders avalable: %player_name%, %damage%, %percentage%, PlaceholderAPI and MvdWPlaceholderAPI placeholders
      message: "    %place_prefix%#%place% - %player_name%&7, Damage: %damage% - %percentage%%"
      title:
        enabled: true
        title: "%mob_name% died."
        subTitle: "1st damage dealt: %mob_top_taken_1%"
        fadeIn: 1
        stay: 1
        fadeOut: 1
      actionbar:
        enabled: true
        message: "%mob_name% died"
    damageTaken:
      header: "&8&l&m------<&r &cMob %mob_name% has died! &8&l&m>------"
      footer: "&8&l&m------&c&l<>&8&l&m---&8&l&m---&c&l<>&8&l&m------"
      message: "    %place_prefix%#%place% - %player_name%&7, Damage: %damage% - %percentage%%"
      title:
        enabled: true
        title: "%mob_name% died."
        subTitle: "1st damage taken: %mob_top_taken_1%"
        fadeIn: 1
        stay: 1
        fadeOut: 1
      actionbar:
        enabled: true
        message: "%mob_name% died"
  Toggle:
    On: "&8<&a!&8>&7 You have successfully &aenabled&7 the broadcaster messages!"
    Off: "&8<&c!&8>&7 You have successfully &cdisabled&7 the broadcaster messages!"

Blacklist:
  #Should the blacklist acted as whitelist?
  Whitelist: false
  Boss:
  - "test"
  MythicMobs:
  - "test"